"""
exporter.py
-----------
"Export to Interactive Maps & PDF" feature.

- generate_kml(): builds a .kml file (Keyhole Markup Language) placing a pin
  for every stop that has coordinates, grouped by day as separate folders.
  KML opens directly in Google My Maps (Import) or Google Earth -- no API
  key or paid service needed, since KML is just a documented open XML format.

- generate_pdf(): builds a clean, print-ready PDF of the day-wise itinerary
  using reportlab (pure Python, no system dependencies like wkhtmltopdf).
"""

import io
from xml.sax.saxutils import escape as xml_escape

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def generate_kml(trip, dest, days_dict):
    """days_dict: {day_number: [sqlite3.Row itinerary_items, ...]}"""
    placemarks_by_day = []
    for day_num in sorted(days_dict.keys()):
        placemarks = []
        for item in days_dict[day_num]:
            lat, lon = item["latitude"], item["longitude"]
            if lat is None or lon is None:
                continue
            name = xml_escape(item["title"])
            desc = xml_escape(f"{item['start_time']} · {item['item_type']} · ₹{item['cost']:.0f}")
            placemarks.append(f"""
    <Placemark>
      <name>{name}</name>
      <description>{desc}</description>
      <Point><coordinates>{lon},{lat},0</coordinates></Point>
    </Placemark>""")
        if placemarks:
            placemarks_by_day.append(f"""
  <Folder>
    <name>Day {day_num}</name>
    {''.join(placemarks)}
  </Folder>""")

    kml = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <name>{xml_escape(dest['name'])} Itinerary — Trip #{trip['id']}</name>
  {''.join(placemarks_by_day)}
</Document>
</kml>"""
    return kml


def generate_pdf(trip, dest, days_dict, total_cost):
    """Returns PDF bytes for the itinerary."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm,
                             leftMargin=2 * cm, rightMargin=2 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=20, spaceAfter=4)
    meta_style = ParagraphStyle("Meta", parent=styles["Normal"], textColor=colors.grey, spaceAfter=14)
    day_style = ParagraphStyle("Day", parent=styles["Heading2"], spaceBefore=16, spaceAfter=6)
    notes_style = ParagraphStyle("Notes", parent=styles["Normal"], fontSize=8.5, textColor=colors.grey)

    elements = []
    elements.append(Paragraph(f"{dest['name']} — {trip['duration_days']}-Day Itinerary", title_style))
    elements.append(Paragraph(
        f"{dest['state']} &middot; {trip['travelers_count']} traveler(s) &middot; "
        f"Trip #{trip['id']} &middot; Total: Rs. {total_cost:,.0f}",
        meta_style
    ))

    for day_num in sorted(days_dict.keys()):
        elements.append(Paragraph(f"Day {day_num}", day_style))
        table_data = [["Time", "Type", "Item", "Cost"]]
        for item in days_dict[day_num]:
            table_data.append([
                item["start_time"] or "",
                item["item_type"].title(),
                Paragraph(xml_escape(item["title"]), styles["Normal"]),
                f"Rs. {item['cost']:,.0f}" if item["cost"] else "-",
            ])
        t = Table(table_data, colWidths=[2.2 * cm, 2.3 * cm, 8.5 * cm, 2.5 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1b2e27")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f0")]),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(t)

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by Trailmark — AI-Based Smart Trip Planner for Community Tourism System.",
        notes_style
    ))

    doc.build(elements)
    buf.seek(0)
    return buf.read()
